### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by drgarcia1986** [kubernetes/kubernetes.github.io#2102]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In second step of interactive tutorial I getting a `panic error` on run `kubectl version`

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"4"
, GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93
c7e0f222d961f4675cd97a46b", GitTreeState:"clean",
 BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1
.6.3", Compiler:"gc", Platform:"linux/amd64"}
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x248b020, 0xc820010020)
        /usr/local/go/src/runtime/panic.go:481 +0
x3e6
k8s.io/kubernetes/pkg/client/typed/discovery.apiV
ersionsToAPIGroup(0xc8203e0640, 0x0, 0x0, 0x0, 0x
0, 0x0, 0x0, 0x37b7c20, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/client/typed/dis
covery/discovery_client.go:101 +0x20e
k8s.io/kubernetes/pkg/client/typed/discovery.(*Di
scoveryClient).ServerGroups(0xc820503580, 0xc8203
494c8, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/client/typed/dis
covery/discovery_client.go:113 +0x1f6
k8s.io/kubernetes/pkg/client/unversioned.Negotiat
eVersion(0xc820073c80, 0xc82034b860, 0x0, 0xc8204
a7000, 0xe, 0x10, 0x3794220, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/client/unversion
ed/helper.go:217 +0x30f
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCa
che).ClientConfigForVersion(0xc8201a2840, 0x0, 0x
0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util
/clientcache.go:80 +0x2e9
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCa
che).ClientForVersion(0xc8201a2840, 0x0, 0x2, 0x0
, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util
/clientcache.go:106 +0xc7
k8s.io/kubernetes/pkg/kubectl/cmd/util.NewFactory
.func3(0xc8203df200, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util
/factory.go:406 +0x35
k8s.io/kubernetes/pkg/kubectl/cmd.RunVersion(0xc8
204757a0, 0x7f4576877210, 0xc820030010, 0xc8203df
200, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/vers
ion.go:48 +0x87
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdVersion.f
unc1(0xc8203df200, 0x37b7c20, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/vers
ion.go:33 +0x49
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(
*Command).execute(0xc8203df200, 0x37b7c20, 0x0, 0
x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/vendor/github.com/sp
f13/cobra/command.go:603 +0x896
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(
*Command).ExecuteC(0xc8201b8900, 0xc8203df200, 0x
0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/vendor/github.com/sp
f13/cobra/command.go:689 +0x55c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(
*Command).Execute(0xc8201b8900, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/vendor/github.com/sp
f13/cobra/command.go:648 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/cmd/kubectl/app/kube
ctl.go:38 +0x11e
main.main()
        /go/src/k8s.io/kubernetes/_output/dockeri
zed/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.
go:26 +0x18
```
**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by BenHall** [comment]
@zacharysarah I believe this can be closed.
